//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanguardia_Projecto_Trazos_Relieves_Grupo5.Modulos
{


    public partial class Reportes
    {
    }
}
